export const item = [
    {
        "id": 1,
        "status": "Pending",
        "guid": "8ddb9f3f-a309-4658-b8ab-38c95cc90a69",
        "remark": "Good Testing",
        "salesId": "P006",
        "createdOn": "2024-09-06T14:01:43+06:30[Asia/Yangon]",
        "shipment": null,
        "quantity": 3,
        "price": 31000.0,
        "originalPrice": 19.99,
        "detailRemark": "Good Testing",
        "detailCreatedOn": "2024-09-06T14:01:43+06:30[Asia/Yangon]",
        "displayName": "blue/1",
        "stockQty": 15,
        "sellQuantity": 5,
        "description": "This is the third product.",
        "buyerFirstName": "Sithu Soe",
        "pageName": "Java Coding",
        "pageGuid": "08948fd5-9bfb-48a7-a122-d2ff4c6ea25a",
        "shippingAddress": "No29",
        "shippingName": "Zay Yar",
        "street": "No(20),Aye Street",
        "townshipName": "အလုံ",
        "deliveryDate": null,
        "primaryPhone": "09795010840",
        "additionalPhone": "09795010840",
        "email": "mailto:bar@gmail.com",
        "country": null,
        "shippingCreatedOn": "2023-05-22T11:25:19+06:30[Asia/Yangon]",
        "countryGuid": null,
        "zipcode": null,
        "townshipNameAlias": "Ahlone",
        "townshipGuid": "1f06a524-05f2-420a-ad87-fa812ffd5104",
        "townshipNameMM": "အလုံ",

    },
    {
        "id": 2,
        "status": "Closed",
        "buyerFirstName": "Amon Soe",
        "townshipNameAlias": "Yankin",
        "sellQuantity": 5,
    },
    {
        "id": 3,
        "status": "Pending",
        "buyerFirstName": "Blue",
        "townshipNameAlias": "Magay",
        "sellQuantity": 8,
    },
    {
        "id": 4,
        "status": "Pending",
        "buyerFirstName": "Yellow",
        "townshipNameAlias": "kachin",
        "sellQuantity": 20,
    },
    {
        "id": 5,
        "status": "Closed",
        "buyerFirstName": "white",
        "townshipNameAlias": "Rhaine",
        "sellQuantity": 2,
    }
]